### ISSUE TITLE
Couchdb 1.1.1

### ISSUE THREAD

**Issue by snsparrish** [iriscouch/build-couchdb#13]
Great project!  Saves me a ton of time.

When  or how can I get this to install version 1.1.1 - I need some of the bug fixes in that version that was released a couple of days ago but build-couchdb is still building 1.1.0.

Thanks so much,
Shawn

**Comment by jhs** [comment]
Whoops! Good point. I upgraded it and pushed.

Since the 1.1.0 release, I changed the git submodule location. It can be a bit of a pain to get this to stick in your own checkout. What I often do is.
1. `git pull`
2. `git status` and make sure it's all nice and clean
3. `rm -rf dependencies/couchdb`
4. `vim .git/config` or your favorite editor. Delete the entire submodule stanza for dependencies/couchdb
5. `git submodule init`
6. `git submodule update`

Actually that is a white lie. What I really do is
1. `cd ..`
2. `rm -rf build-couchdb`
3. `git clone git://github.com/iriscouch/build-couchdb`
4. `cd build-couchdb`
5. `git submodule update --init --recursive`

But either should work.

**Comment by snsparrish** [comment]
Works like a charm.  Thanks so much.

**Comment by jhs** [comment]
You're welcome! Also: charm's don't work, but I think I know what you mean :)
